# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
NULL

sketchfun_cpp <- function(m, n, type = "subGaussian") {
    .Call(`_SKPCA_sketchfun_cpp`, m, n, type)
}

kernelMatrix_cpp <- function(kernel, x) {
    .Call(`_SKPCA_kernelMatrix_cpp`, kernel, x)
}

SKPCA_cpp <- function(X, kernel, d, m, Stype) {
    .Call(`_SKPCA_SKPCA_cpp`, X, kernel, d, m, Stype)
}

update_w <- function(X, A, K, num_fea, Ktype, Kg_h) {
    .Call(`_SKPCA_update_w`, X, A, K, num_fea, Ktype, Kg_h)
}

objfun_Cpp <- function(X, A) {
    .Call(`_SKPCA_objfun_Cpp`, X, A)
}

